# Generated by Django 2.0 on 2019-07-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baner_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=55, null=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Банер')),
                ('mobile_image', models.ImageField(blank=True, upload_to='', verbose_name='Банер мобильная версия')),
                ('active', models.BooleanField(verbose_name='Включен')),
                ('link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на целевую страницу')),
            ],
            options={
                'verbose_name_plural': 'Банеры главная',
                'verbose_name': 'Банер главная',
            },
        ),
    ]
