# Generated by Django 2.0 on 2019-07-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
