# Generated by Django 2.0 on 2019-07-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atr',
            name='xml_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='Внешний ID'),
        ),
        migrations.AddField(
            model_name='atributeproduct',
            name='xml_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='Внешний ID'),
        ),
        migrations.AddField(
            model_name='atrvalue',
            name='xml_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='Внешний ID'),
        ),
        migrations.AddField(
            model_name='brand',
            name='xml_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='Внешний ID'),
        ),
        migrations.AddField(
            model_name='category',
            name='xml_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='Внешний ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='xml_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='Внешний ID'),
        ),
        migrations.AddField(
            model_name='saleatr',
            name='xml_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='Внешний ID'),
        ),
        migrations.AddField(
            model_name='saleatributeproduct',
            name='xml_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='Внешний ID'),
        ),
        migrations.AddField(
            model_name='saleatrvalue',
            name='xml_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='Внешний ID'),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='quantity',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='xml_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='Внешний ID'),
        ),
    ]
