# Generated by Django 2.0 on 2019-07-18 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='new_name',
            field=models.ForeignKey(blank=True, null=True, on_delete='', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
