# Generated by Django 2.0 on 2019-07-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190726_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Адрес '),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete='', to='order.DeliveryMetod', verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete='', to='order.OplataMetod', verbose_name='Способ оплаты'),
        ),
    ]
