# Generated by Django 2.0 on 2019-07-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190726_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='link_image',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Наименование'),
        ),
    ]
