# Generated by Django 2.0 on 2019-07-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0002_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=150, verbose_name='Телефон')),
                ('questions', models.TextField(blank=True, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name_plural': 'Подписки',
                'verbose_name': 'Подписка',
            },
        ),
    ]
